#!/usr/bin/ruby

dir = ARGV.empty? ? "~/Pictures/Wallpapers" : ARGV[0]

paths = `find #{dir}`.split("\n").drop(1).shuffle

paths.map { |file|
  `gsettings set org.gnome.desktop.background picture-uri file:///#{file}`
  sleep 60
}
